### ISSUE TITLE
remove Test Implementations?

### ISSUE THREAD

**Issue by phermsdorf** [ECF/tcpsocketdistributionprovider#6]
Hi @scottslewis ,

i updated my example project to utilize the latest additions we did:
https://github.com/phermsdorf/ecf-consumer-provider-example

As an example i added a pseudo UserManager so that the service implementation can do something with the calling user.

But it does not work currently, because the TestTCPSocketRequestCustomizer and TestTCPSocketServerRequestExecutorCustomizer win against my services because for localhost they are considered and then win because of lower service id.

Since i updated my example bundles i would suggest to remove them and maybe find a good location to point to the examples.

Thanks,
Bye Peter

**Comment by phermsdorf** [comment]
Hi @scottslewis ,

can we continue to work on this? I added the Copyright headers and updated my example projects.
I think you wanted to integrate them to this repository?

Thanks.

Bye Peter

**Comment by scottslewis** [comment]
Hi @phermsdorf 

I've pulled your additions.  Thanks for adding the copyright notices and thanks for doing these examples.

I'm anticipating creating new projects named (for api project):

org.eclipse.ecf.provider.tcpsocket.examples.service.api

in this repo over the next few days.   Let me know if you have any specific desires about namespaces, etc.

**Comment by scottslewis** [comment]
I've now added your service.api, service.consumer, and service.provider in the examples module, made some fixes and updates to common, client, and server bundles, added the examples to the feature, built and committed (to build directory) the 1.4.0 of all bundles and feature to p2 directory.

Please pull these changes, take a look and let me know if there are needed fixes.  I tested using launch configs in example consumer and provider.    And everything was working as desired in the example.

Thanks again for the example code Peter!

**Comment by phermsdorf** [comment]
Hi @scottslewis ,

sorry for being that late with feedback!
Thanks for your adjustments. I'm now trying again to integrate in our project.
I now stumbled about the possibility to configure the used port.
At 

https://github.com/ECF/tcpsocketdistributionprovider/blob/38f6affea49a7a40f811d54a9d5cb543820431d1/bundles/org.eclipse.ecf.provider.tcpsocket.server/src/org/eclipse/ecf/provider/tcpsocket/server/internal/Activator.java#L49-L50C11

you try to get the property for the port from the parameter map, but the map is null which comes from

https://github.com/eclipse/ecf/blob/9264db2cd9569684ec3434e2341f13b08e0e278e/framework/bundles/org.eclipse.ecf/src/org/eclipse/ecf/core/ContainerFactory.java#L255-L257

What would be the suggested way to customize that (from outside)? 
I would like to get that value from a system property or maybe an external configuration file ...

Thanks for your answer.

Bye Peter

**Comment by scottslewis** [comment]
Hi Peter.

The way that remote service properties work (e.g. port) is that any properties that start with
 the service.exported.configs value (e.g. the distribution provider id...in this case

ecf.socket.server

for example:   ecf.socket.server.port are provided in the parameters map, with the ecf.socket.server. stripped off.   (leaving in this case "port").

So, to use a port value of 5555, a service property can be added (to the registered/exported service) like this:

ecf.socket.server.port:Integer=5555

For example, in the HelloService you can specify a port value of 5555 and I've done so in the example here:

https://github.com/ECF/tcpsocketdistributionprovider/blob/master/examples/org.eclipse.ecf.provider.tcpsocket.examples.service.provider/src/org/eclipse/ecf/provider/tcpsocket/examples/service/provider/HelloService.java

The use of the service.exported.config.port idiom is specified by the RSA spec...so that provider-specific properties (e.g. port) and values will be passed into the remote service registration and can be used to configure the remote service.

**Comment by phermsdorf** [comment]
Ok I understand and I now got that working.
I configured the property via ConfigAdmin since the port can be configured externally.

At first i stumbled about the location setting while configuring the properties (some services worked, others not), but the excellent article of Dirk (@fipro78) helped me a lot: https://vogella.com/blog/configuring-osgi-declarative-services/.

I will close this issue for now and create a new one when there are further changes needed.

Thanks again!
Bye Peter
